In [17]:
import numpy as np

#1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [18]:
#2D array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
#arange is used to create array with start stop and step as parameters
d = np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [21]:
e = np.array([1,2,3],dtype = float)
e

array([1., 2., 3.])

In [22]:
#2D and 3D array with arange and reshape
f = np.arange(1,10,1).reshape(3,3)
f.shape
f.ndim

2

In [23]:
g = np.arange(12).reshape(3,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
h = np.arange(16).reshape(2,2,2,2)
h

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [25]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(4,3)
print(np.dot(arr1,arr2))
print()
print(arr1.dot(arr2))
print()
print(arr1@arr2)
print()
print(np.matmul(arr1,arr2))
print()

[[114 120 126]
 [378 400 422]
 [642 680 718]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]



Slicing and Indexing

In [26]:
arr = np.arange(1,10,2)
print(arr)
arr1 =arr[np.array([4,0,2,-1,-2])]
print(arr1)

[1 3 5 7 9]
[9 1 5 9 7]


In [27]:
arr = np.arange(12)
arr1 = arr.reshape(2,2,3)
print(arr1)
print()
print(arr1[1,0,2]) #particular element
print(arr1[1,0]) #1D array
print(arr1[1]) #2D array

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

8
[6 7 8]
[[ 6  7  8]
 [ 9 10 11]]


In [28]:
arr = np.arange(10).reshape(-1,1)
arr.ndim

2

In [29]:
arr = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[9,10,11]]])
print(arr[1,:,1:])
print()
arr1 = arr[:,:,:2]
print(arr1)
print()
print(arr1[:1,1:,:2])
print(arr1[1:,:,:2])
print()
print(arr[0,:,0:3:2])
print(arr[0,:,0::-2])

[[ 6  7]
 [10 11]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 9 10]]]

[[[3 4]]]
[[[ 5  6]
  [ 9 10]]]

[[1 3]
 [3 5]]
[[1]
 [3]]
